version: '4.20'
services: 
  inventorydb:
    container_name: inventory-mysql-container
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=ygz123
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
    volumes:
      - inventorydb:/data/db
  kafka:
    container_name: kafka-container
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
  
volumes:
  inventorydb:
  kafka_data:
      